spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.193.108:3306/xs-school-system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: xiaosenho
    password: 123456
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


